### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by sabawasabi** [sabawasabi/chat-space#22]
# IPアドレス
54.238.172.216

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by sabawasabi** [comment]
確認ありがとう御座います！
LGTMもありがとう御座いました。
